name: 'PR Antora content guidelines checker'
description: 'Checks files updated on PR are following the contribution guideline for an Antora documentation content.'

inputs:
  github-token:
    description: 'The token used to create Pull Request comment when the contribution does not follow requirements'
    required: false
    default: ${{ github.token }}
  site-url:
    description: "The url of preview to check the PR update"
    required: true
  component-name:
    description: "The name of the component to build."
    required: false
    default: "bonita"
  pattern:
    description: ""
    required: false
    default: "modules/**/pages/**/*.adoc"
  # needed by content repository (default master) and here (computed automagically)
  doc-site-branch:
    description: "The branch of the `bonita-documentation-site` used to download js files"
    required: false
    default: "master"

runs:
  using: 'node20'
  main: 'dist/index.js'
