name: 'Notify slack with a message'
description: 'You can customize the message and the channel id.'
inputs:
  CHANNEL_ID:
    description: 'The slack channel id'
    required: true
    default: 'CFD1SMX7V'
  MESSAGE:
    description: 'The message display in first block of notification'
    required: true
    default: ':ok_hand: Action on branch ${{github.ref}} is triggered'
  SLACK_BOT_TOKEN:
    description: 'OAuth token of your slack app'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Send a message to Slack channel
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID}}
        payload: |
          {
              "blocks": [
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": ${{toJSON(inputs.MESSAGE)}}
                      }
                  },
                  {
                      "type": "divider"
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "More details <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>"
                      }
                  }
              ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
