name: 'List branches on repository'
description: 'You can customize the message and the channel id.'
inputs:
  branches_list:
    description: 'Keep branch given in list (separate with space)'
    required: true
    default: 'master dev release-.*'
outputs:
  branches:
    description: "Json object who contains each branch"
    value: ${{ steps.extract_branches.outputs.branches }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: List branches
      shell: bash
      run: |
        git remote set-branches origin '*'
        git fetch
        readarray branches <<< $(git branch --remote --format='%(refname:lstrip=3)' | tr '\n' ' ' | awk '{$1=$1};1')
        json=$(jo -a $branches)
        
        # Create regex from branches list input        
        list_branches=(${{inputs.branches_list}})
        i=0
        for item in "${list_branches[@]}"; do
          list_branches[$i]="^$item$"
          i=$((i+1))
        done
        pattern=$(printf "%s|" "${list_branches[@]}")                    
        
        echo "##[set-output name=branches;]$(echo $json | jq -c 'map(select(test("${pattern%?}")))')"
      id: extract_branches