name: Surge Preview Tools
description: |
  Companion of the surge-preview action.
  It helps to detect if the `surge-preview` action can/should be executed (see outputs).

inputs:
  surge-token:
    description: 'surge.sh token'
    required: false

outputs:
  can-run-surge-command:
    description: 'true if the provided surge-token allows to run surge command'
  domain-exist:
    description: >
      `true` if the domain related to the `preview-url` is publicly available.
      `false` otherwise.
  domain-managed:
    description: >
      `true` if the domain related to the preview-url is managed (i.e. created) by the provided `surge-token`.
      `false` otherwise, in particular the domain was created with another login/token.
  preview-url:
    description: 'The url for the related PR preview, as computed by the surge-preview action'
  surge-token-valid:
    description: 'true if the surge token allow login'

runs:
  using: 'node16'
  main: 'dist/index.js'
