name: Check the Pull Request title
description: Check that the Pull Request title follow the 'Conventional Commits' requirements

inputs:
  github-token:
    description: ''
    required: true
    default: ${{ github.token }}
  comment:
    description: >
      This input controls where the error messages and the fix suggestions are produced.
      If 'true', create a Pull Request comment.
      If 'false', add the messages in the GitHub Actions logs.
      If 'auto', acts like 'false' for Pull Request created from forked repositories. Otherwise, acts like 'true'
    required: true
    default: 'auto'

runs:
  using: "composite"
#  env:
#    POST_PR_COMMENT: ${{}}
  steps:
    - name: Log Pull Request Title
      env:
        # use env var as suggested in https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: echo Checking PR Title "${PR_TITLE}"
#    - name: Compute 'comment' settings
#      uses:
    - uses: jef/conventional-commits-pr-action@v1
      with:
        token: ${{ inputs.github-token }}
        # TODO configure the comments
        comment: true

