name: Check the Pull Request title
description: Check that the Pull Request title follow the 'Conventional Commits' requirements

inputs:
  github-token:
    description: 'The token used to create Pull Request comment when the title does not follow requirements'
    required: true
    default: ${{ github.token }}
  comment:
    description: >
      This input controls where the error messages and the fix suggestions are produced.
      If 'true', create a Pull Request comment.
      If 'false', add the messages in the GitHub Actions logs.
      If 'auto', acts like 'false' for Pull Request created from forked repositories. Otherwise, acts like 'true'
    required: true
    default: 'auto'

runs:
  using: "composite"
  steps:
    - name: Log Pull Request Title
      env:
        # use env var as suggested in https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        PR_TITLE: ${{ github.event.pull_request.title }}
      shell: bash
      run: echo Checking PR Title "${PR_TITLE}"
    - name: Compute 'comment' settings
      uses: actions/github-script@v6
      id: set-pr-comment-option
      env:
        COMMENT_CONFIG: ${{ inputs.comment }}
      with:
        result-encoding: string
        # TODO implement logic
        script: |
          const { COMMENT_CONFIG } = process.env
          console.log(`Original comment config: ${COMMENT_CONFIG}`)
          let effectiveCommentSettings = COMMENT_CONFIG == 'true' || COMMENT_CONFIG == 'auto'
          console.log(`effectiveCommentSettings: ${effectiveCommentSettings}`)
          //console.log(context)
          console.log('PR owner', context.payload.pull_request.owner)
          console.log('Payload repo', context.payload.repository)
          console.log('repo', context.repo)
          return effectiveCommentSettings
    - uses: jef/conventional-commits-pr-action@v1
      with:
        token: ${{ inputs.github-token }}
        comment: ${{ steps.set-pr-comment-option.outputs.result }}

