name: Build PR documentation site actions

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/doc-contribs/*'
      - '!packages/doc-contribs/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/doc-contribs/*'
      - '!packages/doc-contribs/*.md'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'packages/doc-contribs/.nvmrc'
      - name: Install and Test
        run: npm ci && npm run package:all
