name: Build Pr diff checker

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'packages/pr-diff-checker/.nvmrc'
      - name: Install and Test
        run: npm ci && npm test
        working-directory: packages/pr-diff-checker
