name: Build Pr diff checker

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install and Test
        run: npm install && npm run test
        working-directory: packages/pr-diff-checker