name: Build PR documentation site actions

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/doc-contribs/*'
      - '!packages/doc-contribs/*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/doc-contribs/*'
      - '!packages/doc-contribs/*.md'
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'packages/doc-contribs/.nvmrc'
      - name: Install and Test
        run: npm ci && npm run package:all
        working-directory: packages/doc-contribs
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'packages/doc-contribs/!(node_modules)/reports/**/jest-*.xml'
          reporter: jest-junit

