name: Build PR antora content guidelines checker

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/pr-antora-content-guidelines-checker/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/pr-antora-content-guidelines-checker/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'packages/pr-antora-content-guidelines-checker/.nvmrc'
      - name: Install and Test
        run: npm ci && npm run package:all
        working-directory: packages/pr-antora-content-guidelines-checker
