name: Build Pr diff checker

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/pr-diff-checker/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd packages/pr-diff-checker
          npm install

      - name: Run test
        run: npm run test