name: Notify with Slack

on:
  workflow_dispatch:
    inputs:
      channel-id:
        description: 'The id of the channel to notify'
        required: true
        default: CFD1SMX7V # rd-test-bots

jobs:
  notify-slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # only required to access to the local github actions
      - name: Send message to Slack channel
        uses: ./packages/notify-slack
        with:
          CHANNEL_ID: ${{ inputs.channel-id }}
          MESSAGE: |
            :heavy_check_mark: This is a test from the `${{github.repository}}` repository.

            The workflow was triggered manually by `${{github.triggering_actor}}` as `${{github.actor}}`
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
