name: List branches and run matrix job

on:
  workflow_dispatch:

jobs:
  list-branches:
    runs-on: ubuntu-20.04
    steps:
      - name: List branches on repository
        uses: bonitasoft/actions/packages/list-branches@main
        with:
          branche_regex: '^main$|^test-flow$'
  display_branch_name:
    runs-on: ubuntu-20.04
    needs: list-branches
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.list-branches.outputs.branches) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          path: ./repo
          fetch-depth: '1'
      - name: Display branche name
        run: echo "I'm come form ${{ matrix.branch}} branch."