name: Notify with Slack

on:
  workflow_dispatch:
    inputs:
      channel-id:
        description: 'The id of the channel to notify'
        required: true
        default: C02J5M4JMK7 # slack-integration-test

jobs:
  notify-slack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # only required to access to the local github actions
      - name: Send message to Slack channel
        uses: ./packages/notify-slack
        with:
          CHANNEL_ID: ${{ inputs.channel-id }}
          MESSAGE: |
            :fire:  Propagating documentation upwards failed for repository *${{matrix.repo}}*. \n \n  
            @channel *We need someone* ! \n  
            - Add a :fire_extinguisher:if you take the action to resolve the conflicts (only one person is required) \n 
            - Add a :sweat_drops: when it’s done (and eventually a :party_parrot: ) \n \n
            More details on solving the conflicts locally <https://bonitasoft.atlassian.net/wiki/spaces/BS/pages/1181483014/Bonita+documentation+site+content+update#Bonita| there>
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
