name: List branches and run matrix job

on:
  workflow_dispatch:
    inputs:
      branchesList:
        description: 'Branches to run actions'
        required: true
        default: "main"

jobs:
  list-branches:
    runs-on: ubuntu-22.04
    outputs:
      branches: ${{ steps.listBranches.outputs.branches }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4 # access to the local action and list branches of this repository
      - name: List branches on repository
        id: listBranches
        uses: ./packages/list-branches # local action
        with:
          branches_list: ${{ inputs.branchesList }}

  checkout_branch_list:
    runs-on: ubuntu-22.04
    needs: list-branches
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.list-branches.outputs.branches) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          path: ./repo
          fetch-depth: '1'
      - name: Display branch name
        working-directory: ./repo
        run: |
          echo "I'm supposed to be the ${{ matrix.branch}} branch."
          git status
