name: Check PR content

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    name: Check for forbidden string
    steps:
      - name: Scan forbidden string
        uses: bonitasoft/actions/packages/pr-diff-checker@v1.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          diffDoesNotContain: '["http://documentation.mydomain","link:"]'
          extensionsToCheck: '[".adoc"]'
