# Demo/test the pr-diff-checker action
name: Check PR content

on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-22.04
    name: Check for forbidden string
    steps:
      - uses: actions/checkout@v4 # access to the local action
      - name: Scan forbidden string
        uses: ./packages/pr-diff-checker # local action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          diffDoesNotContain: '["http://documentation.mydomain","link:"]'
          extensionsToCheck: '[".adoc"]'
