name: Check Pull Request title

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write # post comments when the PR title doesn't match the "Conventional Commits" rules
    steps:
      - uses: actions/checkout@v3 # access to the local action
      - name: Check pull request title
        uses: ./packages/pr-title-conventional-commits # local action
