# If the tag is v2.4.8 (for example) then this action will create 2 additional tags (v2 and v2.4) and push it.
name: Create major and minor git tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: vweevers/additional-tags-action@v2
